#!/usr/bin/env python3
"""Diagnose and repair the 0.3.2 PostgreSQL secret-newline mismatch.

Default: read-only inspection and a source diff. --apply: back up and correct
01-roles.sql, then reconcile ONLY proven whitespace-mismatched role passwords.
Uses the existing secrets; does not generate passwords, start containers, alter
permissions, run migrations, or touch volumes. Requires host Python 3 and the
running project's PostgreSQL service. See the accompanying README for scope.
"""
from __future__ import annotations

import argparse
import base64
import binascii
import difflib
import hashlib
import hmac
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile

ROLES = {
    'liberty_app': 'postgres_app_password',
    'liberty_metrics': 'postgres_metrics_password',
}
TARGET = Path('docker/postgres/01-roles.sql')


class Refusal(Exception):
    """A deliberately bounded, non-secret diagnostic."""


def regular_file(root: Path, relative: Path | str, limit: int = 1048576) -> Path:
    path = root / relative
    current = root
    for component in Path(relative).parts:
        current = current / component
        if current.is_symlink():
            raise Refusal(f'Refusing symlink in {relative}.')
    if not path.is_file() or path.stat().st_size > limit:
        raise Refusal(f'Missing, oversized, or non-regular file: {relative}.')
    return path


def env_values(root: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for raw in regular_file(root, '.env').read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            raise Refusal('Cannot parse .env. No values were printed.')
        key, value = line.split('=', 1)
        if len(value) >= 2 and value[0] == value[-1] and value[0] in '\"\'':
            value = value[1:-1]
        result[key] = value
    if not re.fullmatch(r'[a-z0-9][a-z0-9_-]{2,63}', result.get('COMPOSE_PROJECT_NAME', '')):
        raise Refusal('An explicit valid COMPOSE_PROJECT_NAME is required in .env.')
    database = result.get('POSTGRES_DB', 'liberty_articulator')
    if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]{0,62}', database):
        raise Refusal('This repair supports only the bundle\'s simple database-name convention.')
    result['POSTGRES_DB'] = database
    return result


def revised_sql(original: str) -> str:
    updated = original
    for secret in ROLES.values():
        old = f"btrim(pg_read_file('/run/secrets/{secret}'))"
        new = f"btrim(pg_read_file('/run/secrets/{secret}'), E' \\t\\r\\n')"
        old_count, new_count = updated.count(old), updated.count(new)
        if old_count == 1 and new_count == 0:
            updated = updated.replace(old, new, 1)
        elif old_count == 0 and new_count == 1:
            continue
        else:
            raise Refusal('Initializer differs from the supported old/new expressions. No overwrite.')
    return updated


def secret_bytes(root: Path, filename: str) -> bytes:
    value = regular_file(root, Path('secrets') / filename, 512).read_bytes()
    # Deliberately exclude arbitrary/custom password encodings. This helper is
    # for the ASCII URL-safe tokens generated by ops/init_secrets.py only.
    if not re.fullmatch(rb'[ \t\r\n]*[A-Za-z0-9_-]{32,256}[ \t\r\n]*', value):
        raise Refusal(f'{filename} is not a supported generated token. No secret value was printed.')
    return value


def matches_scram(verifier: str | None, password: bytes) -> bool:
    """Compare PostgreSQL SCRAM-SHA-256 StoredKey and ServerKey in memory.

    Supported tokens are ASCII. For legacy candidates containing LF/CR/TAB,
    PostgreSQL falls back to the original bytes when SASLprep rejects controls.
    This function never creates a database verifier; psql does that on apply.
    """
    try:
        if not isinstance(verifier, str):
            raise ValueError
        algorithm, params, keys = verifier.split('$')
        iterations_string, salt_string = params.split(':')
        stored_string, server_string = keys.split(':')
        if algorithm != 'SCRAM-SHA-256' or not iterations_string.isdigit():
            raise ValueError
        iterations = int(iterations_string)
        if not 1 <= iterations <= 1000000:
            raise ValueError
        salt = base64.b64decode(salt_string, validate=True)
        stored = base64.b64decode(stored_string, validate=True)
        server = base64.b64decode(server_string, validate=True)
        if not 8 <= len(salt) <= 128 or len(stored) != 32 or len(server) != 32:
            raise ValueError
    except (ValueError, TypeError, binascii.Error):
        raise Refusal('Unsupported or missing SCRAM verifier. Automatic password changes refused.') from None
    salted = hashlib.pbkdf2_hmac('sha256', password, salt, iterations)
    client_key = hmac.digest(salted, b'Client Key', 'sha256')
    calculated_stored = hashlib.sha256(client_key).digest()
    calculated_server = hmac.digest(salted, b'Server Key', 'sha256')
    return (hmac.compare_digest(stored, calculated_stored)
            and hmac.compare_digest(server, calculated_server))


def classify(verifier: str, raw: bytes) -> str:
    normalized = raw.strip()
    if matches_scram(verifier, normalized):
        return 'already-matches'
    legacy = raw.strip(b' ')  # PostgreSQL btrim(text) removes SPACE only.
    if legacy != normalized and matches_scram(verifier, legacy):
        return 'confirmed-whitespace-mismatch'
    raise Refusal('A stored role password matches neither the normalized secret nor the known legacy form. No changes.')


def psql_command(root: Path) -> list[str]:
    # ops/dc preserves this project's existing Compose file order and local config.
    # Non-TTY execution is required so psql password prompts read the private pipe.
    return [sys.executable, str(root / 'ops/dc'), 'exec', '-T', '--user', '70:70',
            'postgres', 'psql', '-X', '-w', '-q', '-A', '-t',
            '-h', '/var/run/postgresql', '-p', '5432', '-U', 'postgres', '-d', 'postgres',
            '-v', 'ON_ERROR_STOP=1', '-v', 'ECHO=none', '-v', 'ECHO_HIDDEN=off',
            '-P', 'pager=off']


def private_run(root: Path, suffix: list[str], input_bytes: bytes) -> bytes:
    env = dict(os.environ)
    env['MODE'] = 'dev'
    env['PYTHONDONTWRITEBYTECODE'] = '1'
    # Avoid unintended Compose auto-profiles while honoring the existing project's
    # supported explicit overlays through ops/dc. exec itself starts no services.
    env.pop('COMPOSE_PROFILES', None)
    try:
        result = subprocess.run(psql_command(root) + suffix, input=input_bytes,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                cwd=root, env=env, timeout=120, start_new_session=True)
    except subprocess.TimeoutExpired:
        raise Refusal('psql timed out. Output withheld; check PostgreSQL status before retrying.') from None
    except OSError:
        raise Refusal('Could not execute the project wrapper or Docker. No child output was printed.') from None
    if result.returncode:
        raise Refusal(f'psql/Compose exited with code {result.returncode}. Raw output withheld to protect secrets; '
                      'check that this project\'s postgres container is running and local postgres administration is available. '
                      'Do not change pg_hba.conf or reset credentials to bypass this check.')
    return result.stdout


def snapshot_sql(database: str) -> bytes:
    # Database name has already been restricted to identifier characters. Secret
    # CONTENTS never enter SQL strings; only hashes of the mounted files are read.
    parts = []
    for role, filename in ROLES.items():
        parts.append(f"""SELECT rolname AS name, rolpassword AS verifier,
            rolcanlogin AS login, rolsuper AS superuser, rolcreatedb AS createdb,
            rolcreaterole AS createrole, rolreplication AS replication,
            rolbypassrls AS bypassrls,
            (rolvaliduntil IS NULL OR rolvaliduntil > CURRENT_TIMESTAMP) AS unexpired,
            ARRAY(SELECT parent.rolname FROM pg_auth_members m
                  JOIN pg_roles parent ON parent.oid = m.roleid
                  WHERE m.member = r.oid ORDER BY parent.rolname) AS memberships,
            encode(sha256(pg_read_binary_file('/run/secrets/{filename}')), 'hex') AS mounted_sha256
            FROM pg_authid r WHERE rolname = '{role}'""")
    query = """BEGIN READ ONLY;
SELECT json_build_object(
  'admin', current_user,
  'superuser', (SELECT rolsuper FROM pg_roles WHERE rolname = current_user),
  'database', (SELECT json_build_object('name', datname,
       'owner', pg_get_userbyid(datdba), 'allow_connections', datallowconn)
       FROM pg_database WHERE datname = '%s'),
  'roles', (SELECT json_agg(row_to_json(details) ORDER BY details.name) FROM (%s) details)
)::text;
ROLLBACK;
""" % (database, '\nUNION ALL\n'.join(parts))
    return query.encode('ascii')


def inspect_database(root: Path, env: dict[str, str], raw: dict[str, bytes]) -> tuple[dict, dict[str, str]]:
    response = private_run(root, ['-f', '-'], snapshot_sql(env['POSTGRES_DB']))
    try:
        state = json.loads(response)
        if state['admin'] != 'postgres' or state['superuser'] is not True:
            raise Refusal('Local database administration did not use the expected postgres superuser.')
        database = state['database']
        if (not database or database['name'] != env['POSTGRES_DB']
                or database['owner'] != 'liberty_app' or database['allow_connections'] is not True):
            raise Refusal('Expected application database/owner is absent or different. No database creation or ownership repair is attempted.')
        rows = state['roles'] or []
        if len(rows) != 2 or {r['name'] for r in rows} != set(ROLES):
            raise Refusal('One of the expected roles is missing. Automatic role creation is refused.')
        status = {}
        for row in rows:
            role = row['name']
            if row['mounted_sha256'] != hashlib.sha256(raw[role]).hexdigest():
                raise Refusal(f'{role}: host secret and PostgreSQL-mounted file differ. No changes.')
            if not row['login'] or not row['unexpired']:
                raise Refusal(f'{role}: login disabled or password validity expired. No changes.')
            if any(row[field] for field in ('superuser', 'createdb', 'createrole', 'replication', 'bypassrls')):
                raise Refusal(f'{role}: privileges differ from the intended unprivileged role. No changes.')
            try:
                status[role] = classify(row['verifier'], raw[role])
            except Refusal as error:
                raise Refusal(f'{role}: {error}') from None
        return state, status
    except (ValueError, TypeError, KeyError):
        raise Refusal('Unexpected inspection response. Raw database output was not displayed or saved.') from None


def credentials_command(roles: list[str], raw: dict[str, bytes]) -> tuple[list[str], bytes]:
    if any(role not in ROLES for role in roles) or len(roles) != len(set(roles)):
        raise Refusal('Unsupported password-update target.')
    # psql performs password encryption before sending ALTER ROLE. Neither the
    # command arguments nor SQL contains a plaintext password.
    args = ['--single-transaction', '-c', "SET LOCAL password_encryption = 'scram-sha-256'"]
    data = b''
    for role in roles:
        args += ['-c', '\\password ' + role]
        data += (raw[role].strip() + b'\n') * 2
    return args, data


def metadata_without_verifiers(state: dict) -> dict:
    copy = json.loads(json.dumps(state))
    for row in copy['roles']:
        row.pop('verifier', None)
    copy['roles'].sort(key=lambda row: row['name'])
    return copy


def backup_and_patch(root: Path, old: bytes, new: bytes) -> Path | None:
    if old == new:
        return None
    target = regular_file(root, TARGET)
    if target.read_bytes() != old:
        raise Refusal('Initializer changed during inspection. No source overwrite.')
    directory = root
    for component in ('runtime', 'patch-backups'):
        directory /= component
        if directory.is_symlink():
            raise Refusal('Refusing symlink in backup path.')
        directory.mkdir(mode=0o700, exist_ok=True)
        if not directory.is_dir():
            raise Refusal('Backup path is not a directory.')
    backup = Path(tempfile.mkdtemp(prefix='postgres-auth-', dir=directory))
    backup.chmod(0o700)
    saved = backup / '01-roles.sql'
    saved.write_bytes(old)
    saved.chmod(0o600)
    descriptor, temporary = tempfile.mkstemp(prefix='.roles-repair-', dir=target.parent)
    try:
        with os.fdopen(descriptor, 'wb') as handle:
            handle.write(new)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, stat.S_IMODE(target.stat().st_mode))
        if target.is_symlink() or target.read_bytes() != old:
            raise Refusal('Initializer changed before replacement. Backup retained; no overwrite.')
        os.replace(temporary, target)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return backup


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project', required=True, type=Path)
    parser.add_argument('--apply', action='store_true', help='Explicitly authorize the source fix and confirmed role-password reconciliation.')
    args = parser.parse_args(argv)
    root = args.project.expanduser().resolve(strict=True)
    for relative in ('ops/dc', 'ops/common.py', 'compose.yaml', 'compose.dev.yaml', 'images.lock.env'):
        regular_file(root, relative)
    env = env_values(root)
    target = regular_file(root, TARGET)
    original = target.read_bytes()
    revised = revised_sql(original.decode('utf-8')).encode('utf-8')
    raw = {role: secret_bytes(root, filename) for role, filename in ROLES.items()}
    print(f"Project: {env['COMPOSE_PROJECT_NAME']}; database: {env['POSTGRES_DB']}")
    print('Inspecting existing roles and mounted-secret identity. Secret values and verifiers are never displayed.')
    before, status = inspect_database(root, env, raw)
    for role in ROLES:
        print(f'{role}: {status[role]}')
    if original != revised:
        print(''.join(difflib.unified_diff(original.decode().splitlines(keepends=True),
                                          revised.decode().splitlines(keepends=True),
                                          fromfile=str(TARGET), tofile=str(TARGET))), end='')
    else:
        print('Initializer source is already corrected.')
    pending = [role for role in ROLES if status[role] == 'confirmed-whitespace-mismatch']
    if not args.apply:
        print('READ-ONLY complete. No source, role passwords, schema, or secret files changed.')
        print('After review, use --apply to correct only confirmed mismatches and the initializer.')
        return 0
    # Recheck secrets and database immediately before the authorized operation.
    if any(secret_bytes(root, ROLES[role]) != raw[role] for role in ROLES):
        raise Refusal('A secret changed during inspection. No changes.')
    latest, latest_status = inspect_database(root, env, raw)
    if latest != before or latest_status != status:
        raise Refusal('Database inspection changed. No changes; rerun read-only inspection.')
    backup = backup_and_patch(root, original, revised)
    if backup:
        print(f'Source corrected. Backup: {backup}')
    if pending:
        print('Reconciling confirmed role passwords to the EXISTING normalized secrets: ' + ', '.join(pending))
        suffix, pipe = credentials_command(pending, raw)
        try:
            private_run(root, suffix, pipe)
        except Refusal as error:
            raise Refusal('Database reconciliation did not finish successfully. The source fix, if applied, remains; '
                          'role changes use a single transaction. Reinspect before resuming. ' + str(error)) from None
    after, after_status = inspect_database(root, env, raw)
    if metadata_without_verifiers(before) != metadata_without_verifiers(after):
        raise Refusal('Post-operation role metadata differs unexpectedly. Stop and inspect; do not run migrations.')
    if any(value != 'already-matches' for value in after_status.values()):
        raise Refusal('Post-operation password verification did not match. Stop before migrations.')
    print('Both role verifiers now match the existing normalized secret files.')
    print('No new passwords, grants, database schema changes, migrations, restarts, or volume operations were performed.')
    print('Next: verify an authenticated query from the migrate service before resuming ops/dev.sh.')
    return 0


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except Refusal as error:
        print('STOP: ' + str(error), file=sys.stderr)
        raise SystemExit(2)
    except (OSError, UnicodeError, ValueError):
        print('STOP: local file/configuration operation failed. Details withheld to avoid secret disclosure. '
              'Do not resume startup until inspected.', file=sys.stderr)
        raise SystemExit(2)
