#!/usr/bin/env python3
"""Generate JSON Schema and TypeScript from Pydantic models. No Django setup required."""
import argparse
import json
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from apps.journal.contracts import SourcesPayload, ArchivePayload, ChronologyPayload

def ts_type(node):
    if '$ref' in node:
        return node['$ref'].split('/')[-1]
    if 'const' in node:
        return json.dumps(node['const'])
    if 'enum' in node:
        return ' | '.join(json.dumps(x) for x in node['enum'])
    if 'anyOf' in node:
        return ' | '.join(ts_type(x) for x in node['anyOf'])
    kind=node.get('type')
    if kind in ('number','integer'): return 'number'
    if kind=='string': return 'string'
    if kind=='boolean': return 'boolean'
    if kind=='null': return 'null'
    if kind=='array': return 'Array<'+ts_type(node['items'])+'>'
    if kind=='object':
        required=set(node.get('required',[]))
        lines=[f'  {json.dumps(k)}'+('' if k in required else '?')+': '+ts_type(v)+';' for k,v in node.get('properties',{}).items()]
        return '{\n'+'\n'.join(lines)+'\n}'
    raise ValueError(f'Unsupported JSON Schema shape: {node!r}')

def outputs():
    definitions={}; out={}
    for name,model in [('sources',SourcesPayload),('archive',ArchivePayload),('chronology',ChronologyPayload)]:
        schema=model.model_json_schema(mode='serialization')
        schema['$schema']='https://json-schema.org/draft/2020-12/schema'
        out[ROOT/f'contracts/{name}.schema.json']=json.dumps(schema,indent=2,sort_keys=True)+'\n'
        for key,value in schema.get('$defs',{}).items():
            if key in definitions and definitions[key] != value:
                raise ValueError('Conflicting contract definition '+key)
            definitions[key]=value
        definitions[model.__name__]=schema
    out[ROOT/'frontend/src/generated/contracts.ts']='// Generated by ops/export_contracts.py. Do not edit by hand.\n\n'+'\n\n'.join(
        f'export type {name} = {ts_type(schema)};' for name,schema in sorted(definitions.items()))+'\n'
    return out

if __name__=='__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    different=[]
    for path,content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text()!=content: different.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content)
    if different: raise SystemExit('Regenerate contracts: '+', '.join(different))
    print('Contracts '+('match.' if args.check else 'generated.'))
